baseURL: https://saigesp.github.io/blog/
languageCode: es-ES
title: Saigesp's Blog
theme: PaperMod

params:
    env: production

    homeInfoParams:
        Title: Aupa! üëã
        Content: >
            Soy Santi, un progamador web con formaci√≥n en dise√±o industrial.

            - En este sitio publico cosas sobre **tecnolog√≠a**, **datos**, y **pol√≠tica**.
            

    socialIcons:
        - name: twitter
          url: https://twitter.com/Saigesp
        - name: github
          url: https://github.com/Saigesp
        - name: other
          url: https://www.dataira.com

    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true
    ShowReadingTime: true
    ShowToc: true
